version: "3.7"
services:

  djangoapp:
    build: .
    command: supervisord
    volumes:
      - ./log:/var/log/tucat
      - ./supervisord/conf.d:/etc/supervisor/conf.d
    env_file:
      tucat/.env
    depends_on:
      - dbtucat
      - mongodb
      - rabbitmq
    networks:
      - nginx_network
      - dbtucat_network
      - mongodb_network
      - rabbitmq_network

  #celery:
  #  build: .
  #  #command: celery worker -l info -A snakeeyes.blueprints.contact.tasks
  #  env_file:
  #      config/.env
  #  depends_on:
  #      - dbtucat
  #      - mongodb
  #      - rabbitmq
  #  networks:
  #      - nginx_network
  #      - dbtucat_network
  #      - mongodb_network
  #      - rabbitmq_network

  dbtucat:
    image: postgres:latest
    volumes:
      - dbtucat_volume:/var/lib/postgresql/data
    env_file:
      - tucat/.env
    networks:
      - dbtucat_network

  mongodb:
    image: mongo:latest
    env_file:
      tucat/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    networks:
      - mongodb_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/staticfiles
      - media:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      tucat/.env
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_network

networks:
  dbtucat_network:
    driver: bridge
  mongodb_network:
    driver: bridge
  nginx_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge

volumes:
  dbtucat_volume:
  mongodb_volume:
  static:
  media:
  rabbitmq_volume:
